export enum JobApplicationStateEnum {
    PENDING = 'PENDING',
    REJECTED = 'REJECTED',
    UNDER_REVIEW = 'UNDER_REVIEW',
    UNDER_CONSIDERATION = 'UNDER_CONSIDERATION',
    ACCEPTED = 'ACCEPTED',
}
